spring.application.name=taskboard

# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/taskboard_db
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=c2VjcmV0a2V5Zm9ydGFza2JvYXJkYXBwbGljYXRpb24xMjM0NTY3OA==
app.jwt.expiration=86400000

# Logging
logging.level.com.taskboard=DEBUG
